language: python

python:
  - "3.4"

sudo: false

services:
  - elasticsearch
  - mysql

before_install:
  - pip install flake8
  - pip install coveralls
  - pip install perceval
  - pip install perceval-mozilla
  - pip install perceval-opnfv
  - pip install pandas
  - pip install sortinghat
  - pip install PyMySQL

# install:
#   - ./setup.py install

script:
  - flake8 .
  - mysqladmin -u root create test_sh
  - mysqladmin -u root create test_projects
  - mysql -u root test_projects < tests/test_projects.sql 
  - echo -e "[ElasticSearch]\nurl=http://localhost:9200" > tests/tests.conf
  - cd tests && ./run_tests.py
